# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180508_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='create_time',
            field=models.IntegerField(),
        ),
    ]
